version: '3'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/
      target: builder
    ports:
      - "80:4200"
    volumes:
      - ./frontend/el-forno:/project
      - /project/node_modules
